from dataclasses import dataclass


@dataclass(slots=True)
class ParametroOperacional:
    chave: str
    valor: float
    estrategia: str
    descricao: str
    id: int | None = None

    @classmethod
    def defaults(cls) -> list["ParametroOperacional"]:
        return [
            cls(chave=k, valor=v["valor"], estrategia=v["estrategia"], descricao=v["descricao"])
            for k, v in cls.PARAMETROS_DEFAULT.items()
        ]

    PARAMETROS_DEFAULT = {
        "taxa_cdi": {"valor": 0.1425, "estrategia": "GERAL", "descricao": "Taxa CDI/Selic (usuario atualiza manualmente na tabela, nao e bug estar fixo)"},
        "premio_risco_box": {"valor": 1.3, "estrategia": "BOX", "descricao": "Premio risco BOX"},
        "premio_risco_sbth": {"valor": 1.1, "estrategia": "SBTH", "descricao": "Premio risco SBTH (ajustavel pelo usuario, nao e bug)"},
        "premio_box_sintetico_call_itm": {"valor": 3.0, "estrategia": "BOX_SINTETICO", "descricao": "Premio BOX sintetico call ITM"},
        "sbth_qtd_ativo": {"valor": 1000, "estrategia": "SBTH", "descricao": "Qtd compra ativo"},
        "sbth_prof_ativo": {"valor": 1, "estrategia": "SBTH", "descricao": "Profundidade book ativo"},
        "sbth_qtd_put": {"valor": 1000, "estrategia": "SBTH", "descricao": "Qtd compra PUT"},
        "sbth_prof_put": {"valor": -1, "estrategia": "SBTH", "descricao": "Profundidade book PUT"},
        "box_qtd_ativo": {"valor": 1000, "estrategia": "BOX", "descricao": "Qtd compra ativo"},
        "box_prof_ativo": {"valor": 1, "estrategia": "BOX", "descricao": "Profundidade book ativo"},
        "box_qtd_put": {"valor": 1000, "estrategia": "BOX", "descricao": "Qtd compra PUT"},
        "box_prof_put": {"valor": -1, "estrategia": "BOX", "descricao": "Profundidade book PUT"},
        "box_qtd_call": {"valor": 1000, "estrategia": "BOX", "descricao": "Qtd venda Call"},
        "box_prof_call": {"valor": 1, "estrategia": "BOX", "descricao": "Profundidade book Call"},
        "basket_qtd_call_itm": {"valor": 100, "estrategia": "BOX_SINTETICO", "descricao": "Qtd compra Call ITM"},
        "basket_prof_call_itm": {"valor": 1, "estrategia": "BOX_SINTETICO", "descricao": "Profundidade Call ITM"},
        "basket_qtd_put": {"valor": 100, "estrategia": "BOX_SINTETICO", "descricao": "Qtd compra PUT"},
        "basket_prof_put": {"valor": -1, "estrategia": "BOX_SINTETICO", "descricao": "Profundidade PUT"},
        "basket_qtd_call": {"valor": 100, "estrategia": "BOX_SINTETICO", "descricao": "Qtd venda Call ATM"},
        "basket_prof_call": {"valor": -1, "estrategia": "BOX_SINTETICO", "descricao": "Profundidade Call ATM"},
        "perf_carga_inteligente": {"valor": 1.0, "estrategia": "PERFORMANCE", "descricao": "Carga Inteligente (Filtro Strike)"},
        "perf_range_min": {"valor": -50.0, "estrategia": "PERFORMANCE", "descricao": "Filtro Strike Min (%)"},
        "perf_range_max": {"valor": 50.0, "estrategia": "PERFORMANCE", "descricao": "Filtro Strike Max (%)"},
        "perf_limite_meses": {"valor": 0.0, "estrategia": "PERFORMANCE", "descricao": "Limite de Vencimento (Meses, 0=Sem Limite)"},
        "perf_dias_minimos": {"valor": 10.0, "estrategia": "PERFORMANCE", "descricao": "Dias Minimos para Vencimento"},
        "onda2_dte_min": {"valor": 7.0, "estrategia": "PERFORMANCE", "descricao": "DTE minimo para registrar Onda 2"},
        "onda2_dte_max": {"valor": 180.0, "estrategia": "PERFORMANCE", "descricao": "DTE maximo para registrar Onda 2"},
        "tema_visual": {"valor": 0.0, "estrategia": "GERAL", "descricao": "Tema Visual (0=Marinho, 1=Grafite, 2=Charcoal)"},
        "rtd_refresh_timeout_ms": {"valor": 5000.0, "estrategia": "GERAL", "descricao": "Timeout do RTD RefreshData em ms (0=sem timeout)"},
        "fonte_market_data": {"valor": "profit", "estrategia": "GERAL", "descricao": "Fonte de market data (profit=Profit RTD via COM, openfast=Open Fast Socket TCP, mock=Dados simulados p/ teste)"},
        "openfast_send_delay_ms": {"valor": 2.0, "estrategia": "GERAL", "descricao": "Delay entre comandos SQT (ms). 0 = delay minimo (1ms)"},
        "taxa_aluguel_habilitado": {"valor": 1.0, "estrategia": "GERAL", "descricao": "Habilitar coleta de taxas de aluguel (InvestSite)"},
        "investsite_timeout_ms": {"valor": 10000.0, "estrategia": "GERAL", "descricao": "Timeout das requisicoes HTTP ao InvestSite (ms)"},
        "investsite_delay_ms": {"valor": 500.0, "estrategia": "GERAL", "descricao": "Delay entre requisicoes ao InvestSite (ms)"},
        "som_arquivo": {"valor": "", "estrategia": "SOM", "descricao": "Arquivo de som .wav para notificacoes (vazio = beep)"},
        "som_volume": {"valor": 100.0, "estrategia": "SOM", "descricao": "Volume do som (0-100%)"},
        "som_arquivo_vendidas": {"valor": "", "estrategia": "SOM", "descricao": "Arquivo de som .wav para VENDIDAS (vazio = beep)"},
        "som_volume_vendidas": {"valor": 100.0, "estrategia": "SOM", "descricao": "Volume do som VENDIDAS (0-100%)"},
        "som_arquivo_coberta": {"valor": "", "estrategia": "SOM", "descricao": "Arquivo de som .wav para VENDA COBERTA (vazio = beep)"},
        "som_volume_coberta": {"valor": 100.0, "estrategia": "SOM", "descricao": "Volume do som VENDA COBERTA (0-100%)"},
        "fonte_tamanho": {"valor": 9.0, "estrategia": "GERAL", "descricao": "Tamanho da fonte do sistema (8-16)"},
        "venda_coberta_premio_risco": {"valor": 1.08, "estrategia": "VENDA_COBERTA", "descricao": "Premio risco minimo sobre CDI para Venda Coberta"},
        "taxa_comprada_dist_max_pct": {"valor": 0.80, "estrategia": "TAXA_COMPRADA", "descricao": "Distancia maxima do strike abaixo do ativo"},
        "taxa_comprada_premio_risco": {"valor": 1.05, "estrategia": "TAXA_COMPRADA", "descricao": "Multiplo minimo do CDI"},
        "taxa_comprada_dias_maximos": {"valor": 10, "estrategia": "TAXA_COMPRADA", "descricao": "Prazo maximo em dias corridos"},
        "taxa_comprada_lote_liquidez": {"valor": 1, "estrategia": "TAXA_COMPRADA", "descricao": "Lote minimo de liquidez"},
        "venda_coberta_lote_liquidez": {"valor": 100.0, "estrategia": "VENDA_COBERTA", "descricao": "Lote minimo de liquidez da CALL para Venda Coberta"},
        "venda_coberta_dias_maximos": {"valor": 30.0, "estrategia": "VENDA_COBERTA", "descricao": "Dias maximos ate o vencimento para TAXA"},
        "venda_coberta_dist_max_pct": {"valor": 0.0, "estrategia": "VENDA_COBERTA", "descricao": "Distancia maxima do strike abaixo do spot (0 = sem minima)"},
        "sbth_vendida_dist_ativo": {"valor": 1.20, "estrategia": "SBTH_VENDIDA", "descricao": "Distancia minima strike/spot (x) - filtro de entrada SBTH Vendida"},
        "vendidas_premio_risco": {"valor": 1.1, "estrategia": "VENDIDAS", "descricao": "Multiplo minimo do CDI para considerar viavel (BOX e SBTH vendidos)"},
        "notif_telegram_enable": {"valor": 0.0, "estrategia": "TELEGRAM", "descricao": "Habilitar Telegram"},
        "telegram_bot_token": {"valor": "0", "estrategia": "TELEGRAM", "descricao": "Token Telegram"},
        "telegram_chat_id": {"valor": "0", "estrategia": "TELEGRAM", "descricao": "Chat ID Telegram"},
        "telegram_cleanup_timeout": {"valor": 300.0, "estrategia": "TELEGRAM", "descricao": "Timeout de limpeza do historico Telegram (segundos)"},
        "premio_risco_colar": {"valor": 0.7, "estrategia": "COLAR", "descricao": "Premio risco Colar (x CDI)"},
        "colar_dist_max_pct": {"valor": 0.15, "estrategia": "COLAR", "descricao": "Distancia maxima do strike (%)"},
        "calendario_strike_diff_max": {"valor": 1.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Max strikes de diferenca entre call e put"},
        "limiar_classificacao_calendario": {"valor": 0.15, "estrategia": "COLLAR_CALENDARIO", "descricao": "Limiar de classificacao (% do spread entre strikes)"},
        "be_search_range_mult": {"valor": 0.15, "estrategia": "COLLAR_CALENDARIO", "descricao": "Margem +/- busca breakeven (ex: 0.15 = 0.85x a 1.15x)"},
        "premio_risco_colar_calendario": {"valor": 0.9, "estrategia": "COLLAR_CALENDARIO", "descricao": "Premio risco Collar Calendario (x CDI)"},
        "calendario_call_otm_max": {"valor": 0.15, "estrategia": "COLLAR_CALENDARIO", "descricao": "Max OTM da call (% do spot)"},
        "taxa_emolumento_pct": {"valor": 0.00025, "estrategia": "GERAL", "descricao": "Taxa de emolumento B3 (% do financeiro)"},
        "taxa_liquidacao_pct": {"valor": 0.000275, "estrategia": "GERAL", "descricao": "Taxa de liquidacao B3 (% do financeiro)"},
        "taxa_registro_pct": {"valor": 0.0001, "estrategia": "GERAL", "descricao": "Taxa de registro B3 para opcoes (% do financeiro)"},
        "taxa_iss_pct": {"valor": 0.0, "estrategia": "GERAL", "descricao": "ISS sobre corretagem (5% tipico = 0.00025 do financeiro)"},
        "taxa_ir_pct": {"valor": 0.15, "estrategia": "GERAL", "descricao": "Aliquota de IR sobre lucro em operacoes (15% swing trade)"},
        "colar_qtd_ativo": {"valor": 100.0, "estrategia": "COLAR", "descricao": "Qtd compra ativo"},
        "colar_prof_ativo": {"valor": 1.0, "estrategia": "COLAR", "descricao": "Profundidade book ativo"},
        "colar_qtd_call": {"valor": 100.0, "estrategia": "COLAR", "descricao": "Qtd venda CALL"},
        "colar_prof_call": {"valor": -1.0, "estrategia": "COLAR", "descricao": "Profundidade book Call"},
        "colar_qtd_put": {"valor": 100.0, "estrategia": "COLAR", "descricao": "Qtd compra PUT"},
        "colar_prof_put": {"valor": -1.0, "estrategia": "COLAR", "descricao": "Profundidade book Put"},
        "calendario_qtd_ativo": {"valor": 100.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Qtd compra ativo"},
        "calendario_prof_ativo": {"valor": 1.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Profundidade book ativo"},
        "calendario_qtd_call": {"valor": 100.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Qtd venda CALL"},
        "calendario_prof_call": {"valor": -1.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Profundidade book Call"},
        "calendario_qtd_put": {"valor": 100.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Qtd compra PUT"},
        "calendario_prof_put": {"valor": -1.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Profundidade book Put"},
        "colar_qul_min_put": {"valor": 100.0, "estrategia": "COLAR", "descricao": "Qtd minima negociada (QUL) para PUT"},
        "colar_qul_min_call": {"valor": 100.0, "estrategia": "COLAR", "descricao": "Qtd minima negociada (QUL) para CALL"},
        "box_premio_risco": {"valor": 1.08, "estrategia": "BOX_4P", "descricao": "Premio risco Box 4P (x CDI)"},
        "box_qtd_min": {"valor": 100, "estrategia": "BOX_4P", "descricao": "Qtd min contratos por perna"},
        "box_soh_europeia": {"valor": 1.0, "estrategia": "BOX_4P", "descricao": "So aceitar opcoes europeias (1=sim, 0=aceita americanas)"},
        "box_scan_interval": {"valor": 5.0, "estrategia": "BOX_4P", "descricao": "Ciclos entre varreduras de Box 4P"},
        "colar_risco_baixo_vov_min": {"valor": 1000.0, "estrategia": "COLAR", "descricao": "VOV/VOC mínimo para risco baixo de despernamento"},
        "elegibilidade_strike_max_pct": {"valor": 0.70, "estrategia": "BOX_SINTETICO", "descricao": "Strike máximo % do spot para elegibilidade de pescaria"},
        "dte_call_min": {"valor": 25.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "DTE mínimo para call no collar calendário"},
        "dte_call_max": {"valor": 60.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "DTE máximo para call no collar calendário"},
        "dte_extra_min": {"valor": 30.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Spread DTE mínimo entre put e call"},
        "dte_extra_max": {"valor": 120.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Spread DTE máximo entre put e call"},
        "dte_total_max": {"valor": 180.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "DTE máximo total para qualquer perna"},
        "import_max_months": {"valor": 9.0, "estrategia": "IMPORTACAO", "descricao": "Meses a frente da data para importar series"},
        "white_list_box4p": {"valor": "", "estrategia": "BOX_4P", "descricao": "Whitelist de ativos para Box 4P"},
        "white_list_colar_calendario": {"valor": "", "estrategia": "COLLAR_CALENDARIO", "descricao": "Whitelist de ativos para Collar Calendario"},
        "white_list_colar": {"valor": "", "estrategia": "COLAR", "descricao": "Whitelist de ativos para Colar Protetivo"},
        "ranking_peso_theta": {"valor": 3.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Peso do theta líquido no ranking (Score)"},
        "ranking_peso_cdi": {"valor": 2.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Peso do %% CDI no ranking (Score)"},
        "ranking_peso_sigma": {"valor": 2.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Peso da folga sigma (distância strikes) no ranking (Score)"},
        "ranking_peso_credito": {"valor": 1.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Peso do crédito líquido no ranking (Score)"},
        "ranking_peso_liquidez": {"valor": 0.5, "estrategia": "COLLAR_CALENDARIO", "descricao": "Peso da liquidez no ranking (Score)"},
        "ranking_peso_colar_pop": {"valor": 3.0, "estrategia": "COLAR", "descricao": "Peso da Pop (probabilidade) no Score do Colar Protetivo"},
        "ranking_peso_colar_cdi": {"valor": 2.0, "estrategia": "COLAR", "descricao": "Peso do %% CDI no Score do Colar Protetivo"},
        "ranking_peso_colar_risco": {"valor": 1.0, "estrategia": "COLAR", "descricao": "Peso do risco de leilão (inverso) no Score do Colar Protetivo"},
        "mpp_oi_peso_absoluto": {"valor": 0.40, "estrategia": "MPP", "descricao": "Peso OI absoluto vs concentracao"},
        "mpp_oi_peso_concentracao": {"valor": 0.60, "estrategia": "MPP", "descricao": "Peso concentracao OI"},
        "mpp_oi_cap_absoluto": {"valor": 10000.0, "estrategia": "MPP", "descricao": "OI cap para normalizacao absoluta"},
        "mpp_curvatura_normalizador": {"valor": 0.10, "estrategia": "MPP", "descricao": "Normalizador curvatura IV (decimal)"},
        "mpp_dte_ideal_min": {"valor": 10.0, "estrategia": "MPP", "descricao": "DTE ideal minimo para pescaria"},
        "mpp_dte_ideal_max": {"valor": 25.0, "estrategia": "MPP", "descricao": "DTE ideal maximo para pescaria"},
        "mpp_dte_fator_min": {"valor": 0.60, "estrategia": "MPP", "descricao": "Fator minimo de DTE (fora da faixa ideal)"},
        "mpp_paridade_normalizador": {"valor": 0.10, "estrategia": "MPP", "descricao": "Normalizador erro de paridade (decimal)"},
        "mpp_habilitado": {"valor": 1.0, "estrategia": "MPP", "descricao": "Habilitar MPP"},
        "mpp_instantaneo_interval": {"valor": 4.0, "estrategia": "MPP", "descricao": "Ciclos entre calculos MPP instantaneos"},
        "mpp_peso_oi": {"valor": 0.15, "estrategia": "MPP", "descricao": "Peso concentração OI"},
        "mpp_peso_volume": {"valor": 0.10, "estrategia": "MPP", "descricao": "Peso baixo volume"},
        "mpp_peso_curvatura_iv": {"valor": 0.10, "estrategia": "MPP", "descricao": "Peso curvatura IV"},
        "mpp_peso_paridade": {"valor": 0.25, "estrategia": "MPP", "descricao": "Peso erro de paridade"},
        "mpp_peso_spread": {"valor": 0.20, "estrategia": "MPP", "descricao": "Peso spread"},
        "mpp_peso_profundidade": {"valor": 0.10, "estrategia": "MPP", "descricao": "Peso profundidade"},
        "mpp_peso_imbalance": {"valor": 0.0, "estrategia": "MPP", "descricao": "Peso book imbalance (descontinuado)"},
        "mpp_peso_spread_anomalia": {"valor": 0.05, "estrategia": "MPP", "descricao": "Peso spread anomalia"},
        "mpp_iv_min_negocios": {"valor": 10.0, "estrategia": "MPP", "descricao": "Núm. mínimo negócios para IV válida"},
        "mpp_iv_min_oi": {"valor": 500.0, "estrategia": "MPP", "descricao": "OI mínimo para IV válida"},
        "mpp_iv_delta_min": {"valor": 0.15, "estrategia": "MPP", "descricao": "Delta mínimo para IV válida"},
        "mpp_iv_delta_max": {"valor": 0.85, "estrategia": "MPP", "descricao": "Delta máximo para IV válida"},
        "mpp_spread_history_len": {"valor": 200.0, "estrategia": "MPP", "descricao": "Tamanho deque spread anomalia"},
        "mpp_spread_min_anomalia": {"valor": 0.02, "estrategia": "MPP", "descricao": "Spread mínimo para anomalia"},
        "mpp_persistencia_max_mult": {"valor": 0.50, "estrategia": "MPP", "descricao": "Multiplicador máximo persistência"},
        "mpp_persistencia_divisor": {"valor": 20.0, "estrategia": "MPP", "descricao": "Ciclos para 1x bônus persistência"},
        "mpp_bonus_max": {"valor": 0.15, "estrategia": "MPP", "descricao": "Bônus máximo histórico"},
        "mpp_bonus_taxa": {"valor": 0.25, "estrategia": "MPP", "descricao": "Taxa conversão sucesso em bônus"},
        "mre_lote_base": {"valor": 100.0, "estrategia": "MPP", "descricao": "Lote base para execução"},
        "mre_profundidade_max_pct": {"valor": 0.20, "estrategia": "MPP", "descricao": "Máximo % da profundidade a consumir"},
        "otimizado_desvios_sigma": {"valor": 2.2, "estrategia": "RATIOS_OTIMIZADOS", "descricao": "Desvios padrao para o range do otimizado"},
        "otimizado_sigma_rendimento": {"valor": 2.0, "estrategia": "RATIOS_OTIMIZADOS", "descricao": "Sigma para exigir CDI no estagio Rendimento"},
        "otimizado_ratio_max": {"valor": 1.3, "estrategia": "RATIOS_OTIMIZADOS", "descricao": "Ratio maximo CALL:ativo permitido"},
        "otimizado_ratio_put_min": {"valor": 0.8, "estrategia": "RATIOS_OTIMIZADOS", "descricao": "Ratio minimo da PUT permitido"},
        "otimizado_ratio_put_step": {"valor": 0.10, "estrategia": "RATIOS_OTIMIZADOS", "descricao": "Passo de varredura dos ratios (LOTE/qtd_acao)"},
        "ranking_peso_iv_rank": {"valor": 25.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Peso do IV Rank no Score IV (0-100)"},
        "ranking_peso_dist_strike": {"valor": 25.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Peso da Dist Strike/Custo no Score IV"},
        "ranking_peso_theta_margin": {"valor": 25.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Peso do Theta/Margin no Score IV"},
        "ranking_peso_vega": {"valor": 10.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Peso do Vega liquido no Score IV"},
        "ranking_peso_liquidez_iv": {"valor": 10.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Peso da Liquidez no Score IV"},
        "ranking_peso_risco_max": {"valor": 5.0, "estrategia": "COLLAR_CALENDARIO", "descricao": "Peso do Risco Max (invertido) no Score IV"},
        "mpp_erro_paridade_limiar": {"valor": 0.02, "estrategia": "MPP", "descricao": "Limiar de erro de paridade para acumular persistencia"},
        "mpp_peso_estrutural": {"valor": 0.35, "estrategia": "MPP", "descricao": "Peso do score estrutural no score final"},
        "mpp_peso_instantaneo": {"valor": 0.65, "estrategia": "MPP", "descricao": "Peso do score instantaneo no score final"},
        "black_list_import": {"valor": "", "estrategia": "IMPORTACAO", "descricao": "Ativos excluidos do ImportFlash"},
        "limite_protecao_pct": {"valor": 0.35, "estrategia": "PROTECAO_CAUDA", "descricao": "Fracao maxima do ganho extra consumida pela protecao"},
        "calda_preco_min_opcao": {"valor": 0.01, "estrategia": "PROTECAO_CAUDA", "descricao": "Preco minimo (R$) da opcao de protecao"},
        "cab_minimo_protecao": {"valor": 1, "estrategia": "PROTECAO_CAUDA", "descricao": "CAB minimo / VOL_ASK minimo para strike candidato"},
        "n_sigma_protecao": {"valor": 2.0, "estrategia": "PROTECAO_CAUDA", "descricao": "Numero de sigmas para s_target da cauda"},
        "fator_seguranca_liquidez": {"valor": 0.2, "estrategia": "PROTECAO_CAUDA", "descricao": "Volume diario minimo como multiplo da qtd comprada"},
        "limite_protecao_pct_rendimento": {"valor": 0.20, "estrategia": "PROTECAO_CAUDA", "descricao": "Fracao do ganho extra para protecao — estagio Rendimento"},
        "limite_protecao_pct_plato": {"valor": 0.45, "estrategia": "PROTECAO_CAUDA", "descricao": "Fracao do ganho extra para protecao — estagio Plato"},
        "limite_protecao_pct_protecao": {"valor": 0.70, "estrategia": "PROTECAO_CAUDA", "descricao": "Fracao do ganho extra para protecao — estagio Protecao"},
        "razao_convexidade_max": {"valor": 1.5, "estrategia": "PROTECAO_CAUDA", "descricao": "Razao maxima de convexidade (qtd/ naked) no estagio Protecao"},
        "spread_maximo_pct": {"valor": 0.20, "estrategia": "PROTECAO_CAUDA", "descricao": "Spread bid-ask maximo para considerar cotacao confiavel"},
        "ex_dividendo_lookback_dias": {"valor": 5.0, "estrategia": "GERAL", "descricao": "Janela (dias uteis) para forcar refresh RTD em ativos ex-dividendo"},
        "venda_coberta_dias_minimos": {"valor": 10.0, "estrategia": "VENDA_COBERTA", "descricao": "Dias minimos ate o vencimento para Venda Coberta"},
        "bwb_modo": {"valor": "simples", "estrategia": "PROTECAO_CAUDA", "descricao": "Modo BWB: 'simples' ou 'borboleta'"},
        "black_list_box4p": {"valor": "", "estrategia": "BOX_4P", "descricao": "Blacklist de ativos para Box 4P"},
        "put_ratio_dte_min": {"valor": 30, "estrategia": "PUT_RATIO", "descricao": "DTE minimo para Put Ratio Spread"},
        "put_ratio_dte_max": {"valor": 50, "estrategia": "PUT_RATIO", "descricao": "DTE maximo para Put Ratio Spread"},
        "put_ratio_iv_rank_min": {"valor": 50.0, "estrategia": "PUT_RATIO", "descricao": "IV minima (%% absoluto) para Put Ratio"},
        "put_ratio_ratios": {"valor": "1x2,2x3,1x3", "estrategia": "PUT_RATIO", "descricao": "Proporcoes a testar (N1xN2 separados por virgula)"},
        "put_ratio_premio_risco": {"valor": 1.5, "estrategia": "PUT_RATIO", "descricao": "Premio risco minimo (x CDI) para Put Ratio"},
        "put_ratio_qtd_min": {"valor": 100, "estrategia": "PUT_RATIO", "descricao": "Qtd minima por perna (book) para Put Ratio"},
        "put_ratio_peso_alpha": {"valor": 0.5, "estrategia": "PUT_RATIO", "descricao": "Peso da protecao (distancia %% BE) no Score"},
        "put_ratio_peso_beta": {"valor": 0.3, "estrategia": "PUT_RATIO", "descricao": "Peso do lucro maximo no Score"},
        "put_ratio_peso_gamma": {"valor": 0.2, "estrategia": "PUT_RATIO", "descricao": "Peso do credito liquido no Score"},
        "put_ratio_min_credit": {"valor": 0.10, "estrategia": "PUT_RATIO", "descricao": "Credito minimo por acao (R$) para considerar"},
        "put_ratio_delta_k1_min": {"valor": -0.55, "estrategia": "PUT_RATIO", "descricao": "Delta minimo da Put comprada (K1)"},
        "put_ratio_delta_k1_max": {"valor": -0.35, "estrategia": "PUT_RATIO", "descricao": "Delta maximo da Put comprada (K1)"},
        "put_ratio_delta_k2_min": {"valor": -0.40, "estrategia": "PUT_RATIO", "descricao": "Delta minimo da Put vendida (K2)"},
        "put_ratio_delta_k2_max": {"valor": -0.03, "estrategia": "PUT_RATIO", "descricao": "Delta maximo da Put vendida (K2)"},
        "white_list_put_ratio": {"valor": "", "estrategia": "PUT_RATIO", "descricao": "Whitelist de ativos para Put Ratio"},
    }
